import streamlit as st

st.set_page_config(
    page_title="Query History - RAG Pipeline",
    layout="wide"
)

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from components import api_client, display_helpers

st.title("Query History")
st.markdown("Review all past questions and the answers generated by the AI.")
st.markdown("---")

limit = st.sidebar.slider("Entries to load", 10, 200, 50, step=10)
search_term = st.sidebar.text_input(
    "Search queries", placeholder="Filter by keyword..."
)

history = api_client.get_query_history(skip=0, limit=limit)

if not history:
    st.info("No query history yet. Ask a question in the Ask Questions page.")
    st.stop()

if search_term:
    search_lower = search_term.lower()
    history = [
        entry for entry in history 
        if search_lower in entry.get("query_text", "").lower()
    ]

st.caption(f"Showing {len(history)} entries.")

for entry in history:
    query_text = entry.get("query_text", "")
    header = f"{query_text[:80]}{'...' if len(query_text) > 80 else ''}"
    if not header:
        header = "Empty Query"
        
    with st.expander(header):
        st.markdown("**Question**")
        st.write(query_text)
        
        st.markdown("**Answer**")
        if entry.get("response_text"):
            display_helpers.render_answer_box(entry["response_text"])
        else:
            st.caption("No answer recorded.")
            
        if entry.get("processing_time_ms"):
            st.caption(f"Processing time: {entry['processing_time_ms']:.0f} ms")
            
        if entry.get("created_at"):
            st.caption(f"Asked at: {entry['created_at']}")
